overrides:
  ajv@<6.14.0: 6.14.0
  brace-expansion@<1.1.18: 1.1.18
  brace-expansion@>=2.0.0 <2.1.4: 2.1.4
  defu@<=6.1.4: 6.1.5
  esbuild@<=0.24.2: 0.25.0
  flatted@<=3.4.1: 3.4.2
  gray-matter>js-yaml: 4.3.1
  lodash@<=4.17.23: 4.18.0
  lodash-es@<=4.17.23: 4.18.0
  minimatch@<3.1.4: 3.1.4
  minimatch@>=9.0.0 <9.0.7: 9.0.7
  nanoid@<3.3.18: 3.3.18
  path-to-regexp@>=8.0.0 <8.4.0: 8.4.0
  picomatch@<2.3.2: 2.3.2
  picomatch@>=4.0.0 <4.0.4: 4.0.4
  postcss@<=8.5.22: 8.5.23
  seroval@<=1.5.2: 1.5.3
  sharp@<0.35.0: 0.35.0

allowBuilds:
  "@heroui-pro/react": true
  "@zowe/secrets-for-zowe-sdk": true
