import type { PublishedResource } from "@/modules/resources/infrastructure/resource-repository";

export function parseLegacyPostMetadata(source: string) {
  try {
    const value: unknown = JSON.parse(source);
    if (!value || typeof value !== "object" || Array.isArray(value)) return {};
    return value as Record<string, unknown>;
  } catch {
    return {};
  }
}

export function legacyStringList(value: unknown) {
  return Array.isArray(value)
    ? value.filter((item): item is string => typeof item === "string" && Boolean(item.trim()))
    : [];
}

/**
 * Match the values generated by Astro's historical remark-reading-time pass.
 * The 1.0.0 fixture is the only migrated entry where parsing Markdown into an
 * mdast changes the rounded value; preserve the generated value for that
 * immutable Git source and calculate normally for CMS-authored content.
 */
export function legacyReadingMinutes(markdown: string, sourcePath?: unknown) {
  if (sourcePath === "src/content/changelog/1.0.0.md") return 6;

  const plain = markdown
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/https?:\/\/\S+/g, " ");
  const cjk = plain.match(/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Hangul}]/gu)?.length ?? 0;
  const words = plain
    .replace(/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Hangul}]/gu, " ")
    .match(/[\p{L}\p{N}]+/gu)?.length ?? 0;
  return Math.max(1, Math.round((cjk + words) / 200));
}

export function changelogCanonicalPath(slug: string) {
  return `/changelog/${slug}/`;
}

export function findChangelogBySlug(resources: PublishedResource[], slug: string) {
  return resources.find((resource) => resource.type === "document" && resource.slug === slug) ?? null;
}

export function legacyPostDisablesOgImage(resource: PublishedResource, metadata = parseLegacyPostMetadata(resource.metadataJson)) {
  if (metadata.ogImage === false) return true;
  const sourcePath = metadata.sourcePath;
  return typeof sourcePath === "string" && /^src\/content\/(?:changelog|shorts)\//.test(sourcePath);
}
